### ISSUE TITLE
Work in Progress: Mistral

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO-Backers-Ships#6]
You said you wanted some WIP shots, so here some are! This is the civilian shuttle I'm making, called the Mistral ([link to the namesake](https://en.wikipedia.org/wiki/Mistral_(wind)), if curious). The exterior is mostly done (just need to put landing gear in the underside), so I thought I'd put some pictures of it up.

![20200429013731_1](https://user-images.githubusercontent.com/33041786/80567820-7d29c300-89bb-11ea-95d2-392504c1d5fc.jpg)

![20200429014905_1](https://user-images.githubusercontent.com/33041786/80569189-05a96300-89be-11ea-9c08-cd8a36f81fbc.jpg)

![20200429014839_1](https://user-images.githubusercontent.com/33041786/80569209-0cd07100-89be-11ea-8cf8-7a2ef7ec2c9f.jpg)

The underside's a bit bland right now; along with adding the gear & finishing the interior, this is on my to-do list.
![20200429020715_1](https://user-images.githubusercontent.com/33041786/80569284-35f10180-89be-11ea-873d-47b92978d50b.jpg)

A couple shots of the WIP interior:
![20200429020808_1](https://user-images.githubusercontent.com/33041786/80569314-502adf80-89be-11ea-8f8c-5e07ad24c714.jpg)

![20200429020801_1](https://user-images.githubusercontent.com/33041786/80569317-528d3980-89be-11ea-98ec-e00d0548fab1.jpg)

Hopefully going to be finished with this in the next couple of days!
![20200429013745_1](https://user-images.githubusercontent.com/33041786/80567805-79963c00-89bb-11ea-97ff-06407a569ad2.jpg)

**Comment by tsunamayo** [comment]
It looks really amazing! Cant wait to put it in the game, now that the landing gear are fixed.
Yes I know mistral well (I guess every french knows it), thats a great name, I think we had a jetfigther named like that.
The volume and detail are really fantastique ;) I need to fix the canopy though...
