### ISSUE TITLE
[WIP] Star Explorers 30m Shuttle

### ISSUE THREAD

**Issue by Sullos** [tsunamayo/Starship-EVO-Backers-Ships#9]
Just booking this post for the WIP of my 30m shuttle. Currently, it has no name, but it is one of several ships that would fall under the civilian corporation known as Star Explorers. The idea is that Star Explorers is a company that maps the galaxy and does research. Sort of like a private research company. 
The shuttle I'm building can be altered in many ways, to meet the requirements that Star Explorers needs. This classification of the shuttle is determined by the colour coding of the symbols on the top of the shuttle, and on the side of the engine pods. If its orange, its an engineering shuttle, equipped with spare parts and repair tools (when we get them), green is a transportation shuttle outfitted with extra seats for passenger transport, red being tactical so it has weapons on it etc.

That's some of the info behind it but here are the pictures. Feedback is of course welcome.

![Starship EVO 2020-05-01 20-02-36-590](https://user-images.githubusercontent.com/33239800/80798609-2523d400-8be8-11ea-8dd2-8a365563efd0.jpg)

![Starship EVO 2020-05-01 20-02-38-640](https://user-images.githubusercontent.com/33239800/80798611-26ed9780-8be8-11ea-87c7-bf68c78309f0.jpg)

![Starship EVO 2020-05-01 20-02-41-215](https://user-images.githubusercontent.com/33239800/80798618-28b75b00-8be8-11ea-9a19-c7beee0ea500.jpg)

![Starship EVO 2020-05-01 20-02-44-018](https://user-images.githubusercontent.com/33239800/80798619-2a811e80-8be8-11ea-9851-f06e74df368d.jpg)

![Starship EVO 2020-05-01 20-02-47-760](https://user-images.githubusercontent.com/33239800/80798625-2c4ae200-8be8-11ea-9fe6-9529ebdc3959.jpg)

![Starship EVO 2020-05-01 20-02-50-158](https://user-images.githubusercontent.com/33239800/80798630-2f45d280-8be8-11ea-9a09-853c1bede5a7.jpg)

![Starship EVO 2020-05-01 20-02-53-916](https://user-images.githubusercontent.com/33239800/80798635-3240c300-8be8-11ea-9c87-ad02f229b594.jpg)

![Starship EVO 2020-05-01 20-02-56-587](https://user-images.githubusercontent.com/33239800/80798638-340a8680-8be8-11ea-8e26-79cd1d060c5e.jpg)

The main corridor running from one side of the ship to the other.
![Starship EVO 2020-05-01 20-03-30-319](https://user-images.githubusercontent.com/33239800/80798644-366ce080-8be8-11ea-8ab3-8a31dd2ac5b7.jpg)

Mini, secondary engineering. Deals with shielding and small cargo storage.
![Starship EVO 2020-05-01 20-03-40-928](https://user-images.githubusercontent.com/33239800/80798648-38cf3a80-8be8-11ea-96cc-b9cf021658fd.jpg)

Kitchen/ eating area.
![Starship EVO 2020-05-01 20-04-00-535](https://user-images.githubusercontent.com/33239800/80798653-3a98fe00-8be8-11ea-9f78-fe32939bca0a.jpg)

Main Engineering, deals with power, logic racks and maybe more if I keep adding to it.
![Starship EVO 2020-05-01 20-04-05-500](https://user-images.githubusercontent.com/33239800/80798655-3c62c180-8be8-11ea-9f08-aed118ac7317.jpg)

Crew bunks. Ship is only intended for 2 people, but as you can see it is fairly spacious, so could be adapted for more. Hence the whole adaptable shuttle talk at the beginning.
![Starship EVO 2020-05-01 20-04-21-730](https://user-images.githubusercontent.com/33239800/80798661-3ff64880-8be8-11ea-86bd-0cdb02f881e1.jpg)

The interior still needs work, along with the ship still needing landing gear and a bit more external decorations I think.
I havent shown the cargo hold, the area on the other side of the big door at the back, nor the cockpit, as both are basically empty.

**Comment by tsunamayo** [comment]
I really like that one! The bulky look fits perfectly, shape is interesting and the interior  looks so cozy! Good job! Cheers
